### ISSUE TITLE
Error occurs when using `_orderby` with built-in functions.

### ISSUE THREAD

**Issue by cncal** [didi/gendry#74]
### The SQL I want to build:

``` sql
SELECT `foo` FROM `bar` ORDER BY RAND() LIMIT 1;
```

### How did I do using `didi/gendry`:

```go
cond, vals, err := builder.BuildSelect(
     "bar",
     map[string]interface{}{
	"_orderby": "RAND()",
	"_limit": []uint{1},
     },
     []string{
	"foo",
     },
)
```

Then an error occurred:
```
[builder] the value of _orderby should be "fieldName direction [,fieldName direction]
```
As stated in [Mysql SELECT Statement](https://dev.mysql.com/doc/refman/8.0/en/select.html) :
```sql
SELECT
    ...
    [ORDER BY {col_name | expr | position}
      [ASC | DESC], ... [WITH ROLLUP]]
```
not only `fieldName direction [,fieldName direction]` can be followed after `ORDER BY`, so should `builder` remove the syntax restriction of operator `_orderby` or just add a new operator which permits users to use some built-in (native) functions?

**Comment by caibirdme** [comment]
Actually it's a delebrately added rule, because the value of `order by` always affects how mysql server choose the index.  In our case, especially in our company, it's forbidden to use `order by rand()`. But, yes, as a common tool, we shouldn't add those limitation just based on our use case. I'll try to update it
Thx for your feedback
